apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - image: okteto.dev/details:{{ .Values.tag }}
        name: details